In [1]:
import torch

In [2]:
t = torch.tensor([[  0,   0, 558],
        [  1,   0, 539],
        [  2,   0, 589],
        [  3,   0, 558],
        [  4,   0, 345],
        [  5,   0, 644],
        [  6,   0, 586],
        [  7,   0, 525],
        [  8,   0, 611],
        [  9,   0, 638],
        [ 10,   0, 654],
        [ 11,   0, 526]], device='cuda:3')


In [7]:
for x, y, z in t:
    print(x)

tensor([  0,   0, 558], device='cuda:3')
tensor([  1,   0, 539], device='cuda:3')
tensor([  2,   0, 589], device='cuda:3')
tensor([  3,   0, 558], device='cuda:3')
tensor([  4,   0, 345], device='cuda:3')
tensor([  5,   0, 644], device='cuda:3')
tensor([  6,   0, 586], device='cuda:3')
tensor([  7,   0, 525], device='cuda:3')
tensor([  8,   0, 611], device='cuda:3')
tensor([  9,   0, 638], device='cuda:3')
tensor([ 10,   0, 654], device='cuda:3')
tensor([ 11,   0, 526], device='cuda:3')
