In [1]:
%load_ext autoreload
%autoreload 2
import os
os.chdir("./../")

In [2]:
from tqdm import tqdm
import datasets
import torch
from datasets import load_dataset
from xent import M
from xent.datasets import SynthProcessor

In [10]:
model = M("base", "gpt2-xl", "M0")

tokenizer path: /rcp/marco/models/base/gpt2-xl/M0
model path: /rcp/marco/models/base/gpt2-xl/M0


Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

In [ ]:
train_set = SynthProcessor(
    base="wiki90-tok",
    dataset_name="train"
).dataset

test_set = SynthProcessor(
    base="wiki90-tok",
    dataset_name="test"
).dataset


Loading data files:  12%|█▎        | 2/16 [00:02<00:16,  1.17s/it]


KeyboardInterrupt: 

In [ ]:
train_set = torch.cat(train_set, dim=-1)
test_set = torch.cat(test_set, dim=-1)

In [ ]:
class WikiTrain(Dataset):
    def __init__(self, tensor, ctx=1024):
        self.data = tensor
        self.ctx = ctx
        self.length = tensor.shape[0] - ctx + 1
    
    def __len__(self):
        return self.length
    
    def __getitem__(self, idx):
        idx = torch.randint(0, self.length, (1,)).item()
        chunk = self.data[idx:idx+self.ctx]
        return chunk 

In [9]:
import pickle
path = "/rcp/marco/data/wiki90-tok/train"
data_files = [f for f in os.listdir(path) if f.endswith(".pkl")]
data = []
for file in data_files: 
    data.append(pickle.load(open(os.path.join(path, file), "rb")))


In [7]:
data

[tensor([[ 2025,   998,  1042,  ...,  4687,  5221, 26770]], device='cuda:1'),
 tensor([[  33,  403, 6248,  ...,  262, 1578, 1829]], device='cuda:1'),
 tensor([[  818,  7096,    78,  ...,  3854,  3961, 12829]], device='cuda:1'),
 tensor([[  198,   198, 37103,  ..., 25631,   762,  5753]], device='cuda:1'),
 tensor([[   40,  4450,   357,  ...,    11, 17711, 32586]], device='cuda:1'),
 tensor([[   43,   377,   620,  ...,   330,   198, 33006]], device='cuda:1'),
 tensor([[  464,   968, 13643,  ..., 27543,  1813,  3891]], device='cuda:1'),
 tensor([[  818,  9156,   290,  ...,   287,  1471, 13808]], device='cuda:1'),
 tensor([[ 7004,    83, 30540,  ..., 29155,  9229,  5270]], device='cuda:1'),
 tensor([[26979,  1136,  3699,  ..., 24402,   198,  6999]], device='cuda:1'),
 tensor([[17688,   642,  2780,  ..., 43293, 28150,  1023]], device='cuda:1'),
 tensor([[15946,  1939,   316,  ...,   286,  1918,  4814]], device='cuda:1'),
 tensor([[   32,  3108,   318,  ..., 16775,  4881,  6685]], device='cu