In [1]:
%load_ext autoreload
%autoreload 2
import os
os.chdir("../")

In [2]:
from xent import M, device
from xent.datasets import Wikipedia
from xent.tasks import Closure

from datasets import load_dataset

In [3]:
model = M("gpt2", "M0")
task = Closure(model)

In [4]:
data = load_dataset(
    "wikipedia", 
    "20220301.en", 
    trust_remote_code=True,
    )["train"]

Loading dataset shards:   0%|          | 0/41 [00:00<?, ?it/s]

In [10]:
import torch
generated = torch.LongTensor([]).to(device)
for n in range(1):
    get_data = lambda: data[n]["text"]
    output = task.generate_parallel_parallel(get_data)

In [11]:
print(model.detokenize(output["xent_rank_top"][0]))

Anarchism is a political philosophy and movement that is sceptical of authority and rejects all involuntary, coercive forms of hierarchy. Anarchism calls for the abolition of the state, which it holds to be unnecessary, undesirable, and harmful. As a historically left-wing movement, placed on the farthest left of the political spectrum, it is usually described alongside communalism and libertarian Marxism as the libertarian wing (libertarian socialism) of the socialist movement, and has a strong historical association with anti-capitalism and socialism.

Humans lived in societies without formal hierarchies long before the establishment of formal states, realms, or empires. With the rise of organised hierarchical bodies, scepticism toward authority also rose. Although traces of anarchist thought are found throughout history, modern anarchism emerged from the Enlightenment. During the latter half of the 19th and the first decades of the 20th century, the anarchist movement flourished in 

: 

In [ ]:
rxent, sort, semicolon = output
semicolon = semicolon.squeeze(0)
lins = torch.cat([model.tokenize(f" {x:.2f}").input_ids for x in rxent])
print(model.detokenize(sort))

sort = sort.view(sort.shape[0],1)

sortandxent = torch.cat([sort[0], lins[0], semicolon])

sort = torch.cat([sort, lins, semicolon.repeat(lins.shape[0], 1)], dim=1)

print(model.detokenize(sort.view(-1)))

# for i in range(1, len(sort)):
#     sortandxent = torch.cat([sortandxent, sort[i], lins[i], semicolon])

 realms placed involuntary scept scept fart traces workers communalHum historicallyarch alongside long hierarchical lived Marxism Various undesirable left organised usually libertarian also emerged establishment holds latter During toward (liber bodies association With modern unnecessary calls wing empires anti most movement socialist hierarchy anarchist states Although historical authority flourished rose Enlightenment As the has decades described first emancipation rejects formal without had socialism and, libertarian societies role political anarchist which is socialism all hierarch forms for formal coercive significant and andcapital anarchist. harmful it parts a)ism found, strong on the a anarchism are as philosophy rise state throughout, the and the, is struggles political a Anarch is, the it or history in authority and and the
 abolition the that,. from of to movement the thought,. and a of the inism, the the movement..- 19 leftismicism half and in forwing'., the. movement world

In [ ]:
import torch

t = torch.Tensor([1.123,2.123,3.123])

s = [f" {round(float(x), ndigits=2)}" for x in t]
i = torch.Tensor([float(x) for x in s])

t = torch.repeat_interleave(t, 2)
t[1::2] = i

t

tensor([1.1230, 1.1200, 2.1230, 2.1200, 3.1230, 3.1200])

In [ ]:
print(model.detokenize(output[-1][0]))

Anarchism is a political philosophy and movement that is sceptical of authority and rejects all involuntary, coercive forms of hierarchy. Anarchism calls for the abolition of the state, which it holds to be unnecessary, undesirable, and harmful. As a historically left-wing movement, placed on the farthest left of the political spectrum, it is usually described alongside communalism and libertarian Marxism as the libertarian wing (libertarian socialism) of the socialist movement, and has a strong historical association with anti-capitalism and socialism.

Humans lived in societies without formal hierarchies long before the establishment of formal states, realms, or empires. With the rise of organised hierarchical bodies, scepticism toward authority also rose. Although traces of anarchist thought are found throughout history, modern anarchism emerged from the Enlightenment. During the latter half of the 19th and the first decades of the 20th century, the anarchist movement flourished in 

In [ ]:
print(model.detokenize(output[0][0]))
print(model.detokenize(output[4][0]))

Anarchism is a political philosophy and movement that is sceptical of authority and rejects all involuntary, coercive forms of hierarchy. Anarchism calls for the abolition of the state, which it holds to be unnecessary, undesirable, and harmful. As a historically left-wing movement, placed on the farthest left of the political spectrum, it is usually described alongside communalism and libertarian Marxism as the libertarian wing (libertarian socialism) of the socialist movement, and has a strong historical association with anti-capitalism and socialism.

Humans lived in societies without formal hierarchies long before the establishment of formal states, realms, or empires. With the rise of organised hierarchical bodies, scepticism toward authority also rose. Although traces of anarchist thought are found throughout history, modern anarchism emerged from the Enlightenment. During the latter half of the 19th and the first decades of the 20th century, the anarchist movement flourished in 

In [ ]:
generated.shape

torch.Size([0])

In [ ]:
generated.shape

torch.Size([0])

In [ ]:
import torch

t = torch.ones(10)
t = t.unfold(0,3,3)

for row in t:
    print(row)


tensor([1., 1., 1.])
tensor([1., 1., 1.])
tensor([1., 1., 1.])


In [ ]:
get_corpus_method = lambda: data.database[91]["text"]

In [ ]:
new_data = task.synthesize(get_corpus_method, 1, out_type="tokens", inverse_order=True)

TypeError: Closure.generate() got an unexpected keyword argument 'inverse_order'

In [ ]:
total = 153
chunks = 30

def schedule(total, chunks):
    if total%chunks != 0:
        return [*[chunks]*(total//chunks), total%chunks]
    else: 
        return [chunks]*(total//chunks)

schedule(total, chunks)

[30, 30, 30, 30, 30, 3]

In [ ]:
workers = 3

def distribute_workers(total, chunks, workers):
    splits = schedule(total, workers)
    return splits
    schedules = [schedule(s, chunks) for s in splits]
    return schedules

total = 100
workers = 3
chunks = 100

per_worker = total // workers
per_worker_schedule = [[*[chunks]*(per_worker//chunks), total%chunks] for _ in range(workers)]

import torch
torch.tensor(per_worker_schedule).sum()

tensor(0)

In [ ]:
def split_into_n(total, n):
    base = total // n
    remainder = total % n
    result = [base] * n
    if remainder:
        result[-1] += remainder
    return result

split_into_n(6458670, 3)  # Returns [33, 33, 34]

[2152890, 2152890, 2152890]