In [1]:
%load_ext autoreload
%autoreload 2
import os
os.chdir("./../../")

In [14]:
from tqdm import tqdm

import torch
import torch.nn.functional as F
from xent.tasks import Closure
from xent import M, T
from xent.datasets import SynthProcessor
from xent.lang import X
from xent.config import *

torch.manual_seed(21)
torch.set_printoptions(threshold=10000)

In [3]:
model = M("crosstalk-cluster", "gpt2", "gpt2-base2closure")

tokenizer path: /rcp/marco/models/base/gpt2/M0
model path: /rcp/marco/models/crosstalk-cluster/gpt2/gpt2-base2closure


In [5]:
data  = SynthProcessor(
    base="parallel_parallel",
    dataset_name="fwd_closure_i",
    # files_to_load=10,
)
# cut the dataset
data.dataset = data.dataset[:3400000]
# shuffle the dataset
data.dataset = data.dataset[torch.randperm(data.dataset.shape[0])]
# train test split
train_set, test_set = data.dataset[:3000000], data.dataset[3000000:3000000+400000]


Loading data files:   0%|          | 0/273 [00:00<?, ?it/s]

Loading data files: 100%|██████████| 273/273 [01:11<00:00,  3.80it/s]


In [6]:
train = T(model, train_set, test_set, batch_size=10, report_wandb=False, eval_size=1000)

In [105]:
from tqdm import tqdm
for i in tqdm(range(100)):
    prompt, output, true, tensor, lenprompt = train.gen_in_loop(split=True)
    if len(output) == 0:
        print("heh dude you messed up")


100%|██████████| 100/100 [15:04<00:00,  9.05s/it]


In [15]:
train.evaluate()

Evaluating the model... 


Testing batch || :   0%|          | 0/100.0 [00:00<?, ?it/s]

tensor([ 4917,   290, 13897,   262,  7659,  5733,  1168,   585,    11,   691,
          284,   307,  6572,   416,   262,  7659,  5733, 20260,  8336,  1031,
          585,    13,   198, 13711,   291,   622,   417,   357, 13038,  3711,
          416,  1526, 13808,   520,  1252,     8,   532,   317,  6715, 16599,
           12, 26966,  9234,  2727,   416,  7695,   271, 15918,   422,   257,
         4048, 25313,   844,  2884,  5536, 16029,   508, 15445,    82,   257,
         5536,  7521, 32680,   326,  3578,   607,   284, 13813,  4970,   290,
         4351,   511,  1176,   284,  1854,    11,  5078,  5920,    11,   290,
          787,  1854,  2121,   287,  1842,   351,   607,    13, 31679,  2645,
         3544, 13711,   291,   622,   417,   287,   257,  7110,   284,   787,
          262, 13804,  2121,   287,  1842,   351,   607,   290, 30981,  1577,
          511,   412, 25649,  5232,   284,   607,    13,  7945,   852, 11791,
          416,  7695,   271, 15918,   290,   370,  3532,    11, 

Testing batch || :   1%|          | 1/100.0 [00:00<00:26,  3.78it/s]

tensor([  262,  6026,   701,    86, 21223,  4752, 44417,    13,   198,   198,
          464,  6026,   701,    86, 21223,   635, 13112,  1104,   329,   262,
         2323,  3386,    11,   351,  3998,   400,  1659,   268,   338,  1610,
          494,  1362,    74,   273,   862, 25197,  7348,  8119,  1104, 10566,
           13,   383,  7570,   604,   400,  5407,   739, 24081, 27086, 23403,
        12769,   550,   663, 10043,  6572,  1474,   347,  2118,    12,    43,
          270,   709,  8135,   416, 12585, 10083,    82,   422,   520,    38,
         8541,    13,   383, 28757,   287,   347,  2118,    12,    43,   270,
          709,  8135,   373,  6572,   416,   281, 21431,  6374, 14918,  5194,
           11,  5710,   416,   509,    38,   513,    13,   383,  2679,  5407,
        11615,   284,  5529,   262, 16511,   618,   340,   750,  6758,   287,
         2207,   343,  8493,  7570, 30648,    13, 18023,    11,   262,  2297,
         5407,  6265,   503,   379,  1755,    11,   832, 17332, 

Testing batch || :   2%|▏         | 2/100.0 [00:00<00:25,  3.80it/s]

tensor([13807, 18320,   265,  2522, 21897,   220,   357, 14508,  1900,   355,
         2462, 18320,   265, 20106,  7833,   290,   319, 10724, 30248,   297,
          283, 41927,   265, 20106,  7833,     8,   318,   257,  1006, 35587,
        21998,  8771,   287,   543,   257, 30248,  8466,   286,   257, 17052,
         1162, 39718,   318, 37100,  4126,  4291,   262, 32700,  4417,   286,
          262,  5827,   338,  1162, 39718,    13,   317, 30248,   297,   283,
         1221,   422,   257, 17052,  1162, 39718,   318,  4624,   625,   262,
          390,    12,   538,   270, 35566,  1143,  2583,  1162, 39718,   290,
          264,   315,  1522,   656,   257,  5597, 35096,   319,   262,  2583,
         1162, 39718,    13,  1423,  3736,  2291,  3513,   286, 41927,   265,
        36221,   385,    11,  1006, 35587,  8563,   588,   616, 24464,   290,
         1029,  8718,  4164,  1773,   544,  1390, 49812, 21897,    11,   543,
         2314,   307, 19267,   351,  5940,  5050,    13,   628, 

Testing batch || :   3%|▎         | 3/100.0 [00:00<00:25,  3.82it/s]

tensor([  379,  9666,   440,  4029,   324,   500,   287,  3944,  9526,   290,
          366, 38432, 25370,    94,  1462, 17266, 32790,    83,   378,   267,
          264,   260, 38325,    72,     1,  5855,  1639,   508,  4320,   286,
        12157, 11074,   198,   198,   464,  7795,  5062, 40584,  8096,   262,
         2647,   262,  4097,  6264,   329,   262, 10343, 32790,   272,   509,
        10071, 46195,  1990,    72, 38325, 13766,   711,   286,   262,   976,
         1438,    13,   383,  5062,  8096,   262,  7259,    11,   366,    43,
           73,   549,   615,     1,  5855, 18565, 12340,  9593,  1085, 25355,
          416,   262, 20495,  8674, 21798,   449,  1990,    83, 47297, 38325,
           11,   290,   366,  5005,    89, 30530,   504,     1,  5855,  5005,
        30530,   415, 12340,   290,   262,  1334,   286,   262,  2716,  2587,
        19954,   286, 21543,  8339,    11,  1390,   257,  3002,  2196,   286,
        32839,  7567,   626,   338, 10797,  2634,   305,    13, 

Testing batch || :   3%|▎         | 3/100.0 [00:01<00:33,  2.89it/s]


KeyboardInterrupt: 

In [ ]:
# if len(output) > 0:
#     print("YES")
#     print(tensor.shape)
#     print(lenprompt)
#     print(tensor[0, lenprompt:].shape)
# else:
#     print("NOPE")
#     print(tensor.shape)
#     print(lenprompt)
#     print(tensor[0, lenprompt:].shape)

# print(prompt)
# print(output[:40])
# print("----------- TRUE ------------")
# print(true[:40])
# print(tensor)
# print(lenprompt)

In [26]:
print(model.detokenize(tensor, "single"))

oner on Psych and another on Supernatural, depicting a malevolent angel called Zachariah. Fuller later reprised the role for Supernatural's 300th episode "Lebanon." He also acted as a Senior Police Officer in the 2000 comedy Scary Movie, who is the commanding officer of Doofy.

In 1986, he played "Frank" in the US premiere of Steven Berkoff's play Kvetch in West Los Angeles. The following year he reprised the role Off-Broadway at the Westside Arts Theater.

From 2010 to 2011, Fuller appeared in the ABC Network series Better with You: the show was canceled after a single season.

Fuller portrayed director of the C.I.A., Grayden Osborne, in the ABC drama Scandal. He also appears in FOX's Us & Them with Jane Kaczmarek and Jason Ritter.

Personal life

Fuller was born in San Francisco, California but raised
@##$$##@ fwd_closure((integer))>:ç%ç>: the:: 5
 Psych: 13
 and: 5
 another: 9
 on: 6
 Super: 9
natural: 1
,: 2
 depicting: 8
 a: 1
 male: 7
volent: 2
 angel: 7
 called: 4
 Zach: 8
ar: 3

In [ ]:
numbers = [" 0"," 1"," 2"," 3"," 4"," 5"," 6"," 7"," 8"," 9"," 10"," 11"," 12"," 13"," 14"," 15"," 16"," 17"," 18"," 19"," 20"]
numtoks = torch.tensor([model.tokenize(num).input_ids for num in numbers]).to(device)
logit_vector = torch.full((model.model.config.vocab_size,), float(-100), device=device)
logit_vector[numtoks.flatten()] = torch.ones(numtoks.flatten().shape[0], device=device) # set to ones instead of random values

# logit_vector = torch.ones(model.model.config.vocab_size, device=device)
# logit_vector[numtoks.flatten()] = torch.rand(numtoks.flatten().shape[0], device=device) * 0.2 + 0.9 # example of a random logits vector

In [ ]:
checker_model.model.eval()
model_loss_on_nums = []
random_loss_on_nums = []

with torch.no_grad():
    for n in tqdm(range(100)):
        
        synth = task.generate(get_test_sample, space="tokens")
        cut, xlen = task.find_xstring(synth, X.xreturn, return_len=True)
        CUT = cut + xlen + 1 # +1 is for the newline \n
        genshift = 1
        
        logits = checker_model.model(synth).logits
        # random_logits = torch.ones_like(logits)
        cut_logits = logits[0, CUT-genshift:-1]
        random_logits = cut_logits.clone()
        # random_logits = random_logits[0, CUT-genshift:-1]

        # print(logits.shape)
        # print(synth.shape)

        for pos in torch.arange(2, cut_logits.shape[0], 4):
            new_random_logits = logit_vector
            new_random_logits[numtoks.flatten()] = torch.rand(numtoks.flatten().shape[0], device=device) * 0.2 + 0.9
            random_logits[pos] = new_random_logits

        model_loss = F.cross_entropy(cut_logits, synth[0, CUT-genshift+1:], reduction="none")
        random_loss = F.cross_entropy(random_logits, synth[0, CUT-genshift+1:], reduction="none")
 
        model_probs = F.softmax(cut_logits, dim=-1)
        highest_prob_tokens = torch.argmax(model_probs, dim=-1)
        model_values, model_indices = torch.topk(cut_logits, k=5)

        random_probs = F.softmax(random_logits, dim=-1)
        random_values, random_indices = torch.topk(random_logits, k=5)
        
        model_tot_loss = model_loss[2::4].mean().item()
        model_loss_on_nums.append(model_tot_loss)

        random_tot_loss = random_loss[2::4].mean().item()
        random_loss_on_nums.append(random_tot_loss)

print(sum(model_loss_on_nums)/len(model_loss_on_nums))
print(sum(random_loss_on_nums)/len(random_loss_on_nums))

100%|██████████| 100/100 [01:26<00:00,  1.16it/s]

2.7929180550575254
3.281314630508423
